### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by AnirudhVyas** [mgentili/goPhat#1]
I need to use chubby to synchronize two services for a go project and a java/scala project, is goPhat well tested, PROD ready and if so could you suggest on how do I use it?

**Comment by nathanielherman** [comment]
Unfortunately it is not prod ready — feel free to use the code if it's helpful though!
    On Wednesday, November 28, 2018, 1:51:41 PM PST, Anirudh Vyas <notifications@github.com> wrote:  
 
 
I need to use chubby to synchronize two services for a go project and a java/scala project, is goPhat well tested, PROD ready and if so could you suggest on how do I use it?

**Comment by AnirudhVyas** [comment]
Thanks for letting me know.
